Numpy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster Operation

In [1]:
import numpy as np


List vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0015783070000008337


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0008946120000015156


Numpy Arrays


In [6]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [13]:
#create a numpy arrat of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
#create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.11227505 0.45600457 0.27053234 0.91955838]
 [0.10919487 0.17972887 0.33258808 0.53209938]
 [0.63227994 0.04539582 0.08957357 0.44954585]]


In [20]:
#random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[58 84 56 94 41]
 [29 48 86 49 20]
 [76 34 18 75 93]]


In [22]:
#array of evenly spaced values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [24]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [25]:
#convert a list to a take numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [26]:
c = np.random.randint(10,90,(5,5))
print(c)

[[26 53 62 89 58]
 [59 87 58 44 20]
 [33 37 24 63 31]
 [58 47 81 40 24]
 [67 24 76 68 85]]


In [29]:
#array dimension
print(c.shape)

(5, 5)


In [30]:
#number of dimensions
print(c.ndim)

2


In [31]:
#number of elements in an array
print(c.size)

25


In [32]:
#checking  the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [33]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) ## concatenate or jooins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0, 10,(3,3))
b = np.random.randint(10, 20(3,3))

In [46]:
print(a)
print(b)

[[2 3 1]
 [0 1 5]
 [7 4 5]]
[[0.11227505 0.45600457 0.27053234 0.91955838]
 [0.10919487 0.17972887 0.33258808 0.53209938]
 [0.63227994 0.04539582 0.08957357 0.44954585]]


In [48]:
print(a + b[:, :3])
print(a - b[:, :3])
print(a * b[:, :3])
print(a / b[:, :3])

[[2.11227505 3.45600457 1.27053234]
 [0.10919487 1.17972887 5.33258808]
 [7.63227994 4.04539582 5.08957357]]
[[ 1.88772495  2.54399543  0.72946766]
 [-0.10919487  0.82027113  4.66741192]
 [ 6.36772006  3.95460418  4.91042643]]
[[0.22455009 1.3680137  0.27053234]
 [0.         0.17972887 1.66294041]
 [4.42595956 0.18158328 0.44786787]]
[[17.81339736  6.57888148  3.69641576]
 [ 0.          5.56393644 15.03361142]
 [11.07104559 88.11383823 55.82003518]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20(3,3))

In [49]:
print(a)
print(b)

[[2 3 1]
 [0 1 5]
 [7 4 5]]
[[0.11227505 0.45600457 0.27053234 0.91955838]
 [0.10919487 0.17972887 0.33258808 0.53209938]
 [0.63227994 0.04539582 0.08957357 0.44954585]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

Array Manipulation


In [55]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[4 4 2]
 [3 2 4]]
(2, 3)


In [56]:
#transpose
trans = np.transpose(array)
print(trans)
print(array.shape)

[[4 3]
 [4 2]
 [2 4]]
(2, 3)


In [57]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 3]
 [4 2]
 [2 4]]
(3, 2)


In [58]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 0 8]
 [1 2 6]]
(2, 3)


In [59]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 0]
 [8 1]
 [2 6]]
(3, 2)
